coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: "diff, files"
  require_changes: true

fixes:
  - "meep/::python/"
