#!/bin/sh

set -ev

sh autogen.sh --verbose

version=`grep PACKAGE_VERSION config.h |cut -d' ' -f3 |tr -d \"`
distdir="meep-$version"
tarfile="${distdir}.tar.gz"

make dist

tar xzf $tarfile
rm $tarfile

cd $distdir
make
make check
cd ..

rm -rf $distdir */latest_output

