site_name: MEEP documentation
site_author: Homer Reid
site_favicon: meep.ico

repo_url: https://github.com/stevengj/meep/

theme_dir: 'meep-mkdocs-theme'

python:
   version: 2 # for unicode
   setup_py_install: True

markdown_extensions:
    - wikilinks
    - toc:
        title: Table of Contents
    - attr_list
    - fenced_code
    - mdx_math:
        enable_dollar_delimiter: True

extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','mathjaxhelper.js']

pages:
- Top-level page:     'index.md'
- MEEP documentation: 'Meep.md'
