name: Sphinx docs to gh-pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.10.0
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: anaconda-client-env
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Installing the library
        shell: bash -l {0}
        run: |
          pip install -e .
          pip install -r requirements_dev.txt
          sudo wget https://github.com/jgm/pandoc/releases/download/1.16.0.2/pandoc-1.16.0.2-1-amd64.deb
          sudo dpkg -i pandoc-1.16.0.2-1-amd64.deb
          #sudo apt install pandoc
      - name: Running the Sphinx to gh-pages Action
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v1.0-beta.2
        with:
          branch: master
          dir_docs: docs
          sphinxopts: ""
