---
name: test with updated requirements (bleeding edge versions)
# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python

on:
  pull_request:
  push:
  schedule:
    - cron: 0 2 * * * # run at 2 AM UTC

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 12
      matrix:
        python-version: [3.9]
        os: [ubuntu-latest]

    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pur pytest
          pur -r requirements.txt
          pip install .
      - name: Test with pytest
        run: pytest
